[package]
name = "gateway"
version = "0.2.1"
authors = ["airtrack <airtrack.sk@gmail.com>"]
edition = "2024"

[dependencies]
log = "0.4"
pnet = "0.34.0"
tokio = { version = "1.38.0", features = ["full"] }
bytes = "1"
dashmap = "6.1"
rand = "0.9"
